### ISSUE TITLE
[BUG] Android 14 SecurityException Specify RECEIVER_EXPORTED

### ISSUE THREAD

**Issue by AlexanderThiele** [surfstudio/flutter-otp-autofill#70]
App does not work on Android 14 devices.
```
targetSdkVersion 34
compileSdkVersion 34
```

**Comment by kartik0198** [comment]
Hi, when will this be merged? Facing crashes in A14 devices due to this.

**Comment by AlexanderThiele** [comment]
@kartik0198 Meanwhile, you can do it like this:
```yaml
  otp_autofill:
    git:
      url: https://github.com/AlexanderThiele/flutter-otp-autofill
```

and move back to the update whenever it's merged
